name: Run Code Review

on:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install github
          pip install requests

      - name: Run Code Review Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo'
          PROMPT: 'Please review the code below and provide feedback.'
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs cat > code_to_review.py
          python code_review_script.py
